In [1]:
import numpy as np

In [12]:
a =np.random.randint(1,10, (2, 5))
b =np.random.randint(1,10, (2, 5))

In [13]:
a

array([[7, 2, 3, 9, 2],
       [4, 5, 9, 8, 1]])

In [14]:
b

array([[3, 4, 5, 7, 3],
       [4, 6, 1, 3, 6]])

In [15]:
a + b

array([[10,  6,  8, 16,  5],
       [ 8, 11, 10, 11,  7]])

In [ ]:
## Broadcasting rules
# Shape should be same, start checking from the Right
#  if it has 1, it will work
#